### ISSUE TITLE
broken link on first page: go content mine

### ISSUE THREAD

**Issue by jibe-b** [ContentMine/contentmine.github.io#1]
Hi,

On the http://contentmine.org/ index page, the big button "Go content mine" is on a broken link:
http://contentmine.orggo-contentmine/
that should pobably be:
http://contentmine.org/go-contentmine/

Best regards,

jibe

**Comment by GrahamSteel** [comment]
Thanks. I don't have editing access to that page.
@skasberger - can you please fix or give me access to that page. Thanks.

**Comment by GrahamSteel** [comment]
Issue resolved.
