### ISSUE TITLE
problem with md files?

### ISSUE THREAD

**Issue by robldavidson** [ContentMine/contentmine.github.io#2]
In your linux/osx/windows.md files, there are commands such as:

{% include run-getpapers.md %}

I was initially uncertain whether these were cryptic instructions for additions to make to Node but it looks like these are references to segments of document elsewhere in the file structure... Is there a best way to read these?

**Comment by tarrow** [comment]
Hi,

This is the way templates are formatted in liquid https://github.com/Shopify/liquid which is the templating engine jekyll uses. Jekyll is what github uses to build github pages sites. This is a github pages site repository which means github generates a website from the markdown files (and other bits and pieces here)

If you're looking for where to read the actual documentation then you want to go the where this site is rendered http://contentmine.github.io.

Am I right in thinking that is what you were looking for? Do you think a bit of text explaining this should be in the README.md for this repository itself?

Tom

**Comment by blahah** [comment]
I just set the website for this repo, so it displays at the top of the page. Adding it to the README also makes sense.

**Comment by robldavidson** [comment]
Hi, yeah, I think it's better now that there is a link to 'you can view this here'. I've looked at Jekyll in the past and the notation was familiar but there are so many languages that I do find it hard to remember what I'm looking at unless it's specified.

**Comment by tarrow** [comment]
Hopefully, this is a little clearer so I'm going to close :)
